version: '3'
networks:
  beetle_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
services:
  user-db:
    image: mysql:8
    labels:
      kompose.volume.type: persistentVolumeClaim
    hostname: user-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
      - "3306"
    volumes:
      - /data/docker/mount/beetle_user_db:/var/lib/mysql
    networks:
      beetle_network:
        ipv4_address: 192.168.16.100
  user-svc:
    build:
      context: .
      args:
        APP: user
    image: beetle/user:0.0.1
    labels:
      kompose.volume.type: configMap
    hostname: user-svc
    volumes:
      - ./app/user/configs:/data/conf
    expose:
      - "8000"
      - "9000"
    depends_on:
      - user-db
    networks:
      beetle_network:
        ipv4_address: 192.168.16.101
  im-db:
    image: mysql:8
    labels:
      kompose.volume.type: persistentVolumeClaim
      kompose.service.type: loadbalancer
    hostname: im-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - /data/docker/mount/beetle_im_db:/var/lib/mysql
    networks:
      beetle_network:
        ipv4_address: 192.168.16.102
  im-svc:
    build:
      context: .
      args:
        APP: im
    image: beetle/im:0.0.1
    labels:
      kompose.volume.type: configMap
    hostname: im-svc
    volumes:
      - ./app/im/configs:/data/conf
    expose:
      - "9000"
      - "10000"
    depends_on:
      - im-db
    networks:
      beetle_network:
        ipv4_address: 192.168.16.103
  im-redis:
    image: redis:4.0.1
    labels:
      kompose.volume.type: persistentVolumeClaim
      kompose.service.type: loadbalancer
    hostname: im-redis
    ports:
      - "6379:6379"
    volumes:
      - ./deploy/docker/im/redis/data:/data
      - ./deploy/docker/im/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./deploy/docker/im/redis/logs:/logs
    networks:
      beetle_network:
        ipv4_address: 192.168.16.103
  gateway:
    build:
      context: .
      args:
        APP: gateway
    image: beetle/gateway:0.0.1
    labels:
      kompose.volume.type: configMap
      kompose.service.type: loadbalancer
    hostname: gateway
    volumes:
      - ./app/gateway/configs:/data/conf
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - user-svc
    networks:
      beetle_network:
        ipv4_address: 192.168.16.200
