// Code generated by ent, DO NOT EDIT.

package ent

import (
	"beetle/app/im/internal/data/ent/personalchatmessage"
	"beetle/app/im/internal/data/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PersonalChatMessageQuery is the builder for querying PersonalChatMessage entities.
type PersonalChatMessageQuery struct {
	config
	ctx        *QueryContext
	order      []personalchatmessage.OrderOption
	inters     []Interceptor
	predicates []predicate.PersonalChatMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PersonalChatMessageQuery builder.
func (pcmq *PersonalChatMessageQuery) Where(ps ...predicate.PersonalChatMessage) *PersonalChatMessageQuery {
	pcmq.predicates = append(pcmq.predicates, ps...)
	return pcmq
}

// Limit the number of records to be returned by this query.
func (pcmq *PersonalChatMessageQuery) Limit(limit int) *PersonalChatMessageQuery {
	pcmq.ctx.Limit = &limit
	return pcmq
}

// Offset to start from.
func (pcmq *PersonalChatMessageQuery) Offset(offset int) *PersonalChatMessageQuery {
	pcmq.ctx.Offset = &offset
	return pcmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pcmq *PersonalChatMessageQuery) Unique(unique bool) *PersonalChatMessageQuery {
	pcmq.ctx.Unique = &unique
	return pcmq
}

// Order specifies how the records should be ordered.
func (pcmq *PersonalChatMessageQuery) Order(o ...personalchatmessage.OrderOption) *PersonalChatMessageQuery {
	pcmq.order = append(pcmq.order, o...)
	return pcmq
}

// First returns the first PersonalChatMessage entity from the query.
// Returns a *NotFoundError when no PersonalChatMessage was found.
func (pcmq *PersonalChatMessageQuery) First(ctx context.Context) (*PersonalChatMessage, error) {
	nodes, err := pcmq.Limit(1).All(setContextOp(ctx, pcmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{personalchatmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) FirstX(ctx context.Context) *PersonalChatMessage {
	node, err := pcmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PersonalChatMessage ID from the query.
// Returns a *NotFoundError when no PersonalChatMessage ID was found.
func (pcmq *PersonalChatMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcmq.Limit(1).IDs(setContextOp(ctx, pcmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{personalchatmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := pcmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PersonalChatMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PersonalChatMessage entity is found.
// Returns a *NotFoundError when no PersonalChatMessage entities are found.
func (pcmq *PersonalChatMessageQuery) Only(ctx context.Context) (*PersonalChatMessage, error) {
	nodes, err := pcmq.Limit(2).All(setContextOp(ctx, pcmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{personalchatmessage.Label}
	default:
		return nil, &NotSingularError{personalchatmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) OnlyX(ctx context.Context) *PersonalChatMessage {
	node, err := pcmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PersonalChatMessage ID in the query.
// Returns a *NotSingularError when more than one PersonalChatMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (pcmq *PersonalChatMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcmq.Limit(2).IDs(setContextOp(ctx, pcmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{personalchatmessage.Label}
	default:
		err = &NotSingularError{personalchatmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := pcmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PersonalChatMessages.
func (pcmq *PersonalChatMessageQuery) All(ctx context.Context) ([]*PersonalChatMessage, error) {
	ctx = setContextOp(ctx, pcmq.ctx, "All")
	if err := pcmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PersonalChatMessage, *PersonalChatMessageQuery]()
	return withInterceptors[[]*PersonalChatMessage](ctx, pcmq, qr, pcmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) AllX(ctx context.Context) []*PersonalChatMessage {
	nodes, err := pcmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PersonalChatMessage IDs.
func (pcmq *PersonalChatMessageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pcmq.ctx.Unique == nil && pcmq.path != nil {
		pcmq.Unique(true)
	}
	ctx = setContextOp(ctx, pcmq.ctx, "IDs")
	if err = pcmq.Select(personalchatmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := pcmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pcmq *PersonalChatMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pcmq.ctx, "Count")
	if err := pcmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pcmq, querierCount[*PersonalChatMessageQuery](), pcmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) CountX(ctx context.Context) int {
	count, err := pcmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pcmq *PersonalChatMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pcmq.ctx, "Exist")
	switch _, err := pcmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pcmq *PersonalChatMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := pcmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PersonalChatMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pcmq *PersonalChatMessageQuery) Clone() *PersonalChatMessageQuery {
	if pcmq == nil {
		return nil
	}
	return &PersonalChatMessageQuery{
		config:     pcmq.config,
		ctx:        pcmq.ctx.Clone(),
		order:      append([]personalchatmessage.OrderOption{}, pcmq.order...),
		inters:     append([]Interceptor{}, pcmq.inters...),
		predicates: append([]predicate.PersonalChatMessage{}, pcmq.predicates...),
		// clone intermediate query.
		sql:  pcmq.sql.Clone(),
		path: pcmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PersonalChatMessage.Query().
//		GroupBy(personalchatmessage.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pcmq *PersonalChatMessageQuery) GroupBy(field string, fields ...string) *PersonalChatMessageGroupBy {
	pcmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PersonalChatMessageGroupBy{build: pcmq}
	grbuild.flds = &pcmq.ctx.Fields
	grbuild.label = personalchatmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PersonalChatMessage.Query().
//		Select(personalchatmessage.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (pcmq *PersonalChatMessageQuery) Select(fields ...string) *PersonalChatMessageSelect {
	pcmq.ctx.Fields = append(pcmq.ctx.Fields, fields...)
	sbuild := &PersonalChatMessageSelect{PersonalChatMessageQuery: pcmq}
	sbuild.label = personalchatmessage.Label
	sbuild.flds, sbuild.scan = &pcmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PersonalChatMessageSelect configured with the given aggregations.
func (pcmq *PersonalChatMessageQuery) Aggregate(fns ...AggregateFunc) *PersonalChatMessageSelect {
	return pcmq.Select().Aggregate(fns...)
}

func (pcmq *PersonalChatMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pcmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pcmq); err != nil {
				return err
			}
		}
	}
	for _, f := range pcmq.ctx.Fields {
		if !personalchatmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pcmq.path != nil {
		prev, err := pcmq.path(ctx)
		if err != nil {
			return err
		}
		pcmq.sql = prev
	}
	return nil
}

func (pcmq *PersonalChatMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PersonalChatMessage, error) {
	var (
		nodes = []*PersonalChatMessage{}
		_spec = pcmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PersonalChatMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PersonalChatMessage{config: pcmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pcmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pcmq *PersonalChatMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pcmq.querySpec()
	_spec.Node.Columns = pcmq.ctx.Fields
	if len(pcmq.ctx.Fields) > 0 {
		_spec.Unique = pcmq.ctx.Unique != nil && *pcmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pcmq.driver, _spec)
}

func (pcmq *PersonalChatMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(personalchatmessage.Table, personalchatmessage.Columns, sqlgraph.NewFieldSpec(personalchatmessage.FieldID, field.TypeInt))
	_spec.From = pcmq.sql
	if unique := pcmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pcmq.path != nil {
		_spec.Unique = true
	}
	if fields := pcmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personalchatmessage.FieldID)
		for i := range fields {
			if fields[i] != personalchatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pcmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pcmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pcmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pcmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pcmq *PersonalChatMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pcmq.driver.Dialect())
	t1 := builder.Table(personalchatmessage.Table)
	columns := pcmq.ctx.Fields
	if len(columns) == 0 {
		columns = personalchatmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pcmq.sql != nil {
		selector = pcmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pcmq.ctx.Unique != nil && *pcmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pcmq.predicates {
		p(selector)
	}
	for _, p := range pcmq.order {
		p(selector)
	}
	if offset := pcmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pcmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PersonalChatMessageGroupBy is the group-by builder for PersonalChatMessage entities.
type PersonalChatMessageGroupBy struct {
	selector
	build *PersonalChatMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pcmgb *PersonalChatMessageGroupBy) Aggregate(fns ...AggregateFunc) *PersonalChatMessageGroupBy {
	pcmgb.fns = append(pcmgb.fns, fns...)
	return pcmgb
}

// Scan applies the selector query and scans the result into the given value.
func (pcmgb *PersonalChatMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcmgb.build.ctx, "GroupBy")
	if err := pcmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PersonalChatMessageQuery, *PersonalChatMessageGroupBy](ctx, pcmgb.build, pcmgb, pcmgb.build.inters, v)
}

func (pcmgb *PersonalChatMessageGroupBy) sqlScan(ctx context.Context, root *PersonalChatMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pcmgb.fns))
	for _, fn := range pcmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pcmgb.flds)+len(pcmgb.fns))
		for _, f := range *pcmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pcmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PersonalChatMessageSelect is the builder for selecting fields of PersonalChatMessage entities.
type PersonalChatMessageSelect struct {
	*PersonalChatMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pcms *PersonalChatMessageSelect) Aggregate(fns ...AggregateFunc) *PersonalChatMessageSelect {
	pcms.fns = append(pcms.fns, fns...)
	return pcms
}

// Scan applies the selector query and scans the result into the given value.
func (pcms *PersonalChatMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcms.ctx, "Select")
	if err := pcms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PersonalChatMessageQuery, *PersonalChatMessageSelect](ctx, pcms.PersonalChatMessageQuery, pcms, pcms.inters, v)
}

func (pcms *PersonalChatMessageSelect) sqlScan(ctx context.Context, root *PersonalChatMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pcms.fns))
	for _, fn := range pcms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pcms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
