// Code generated by ent, DO NOT EDIT.

package ent

import (
	"beetle/app/im/internal/data/ent/predicate"
	"beetle/app/im/internal/data/ent/synchronizerecord"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SynchronizeRecordDelete is the builder for deleting a SynchronizeRecord entity.
type SynchronizeRecordDelete struct {
	config
	hooks    []Hook
	mutation *SynchronizeRecordMutation
}

// Where appends a list predicates to the SynchronizeRecordDelete builder.
func (srd *SynchronizeRecordDelete) Where(ps ...predicate.SynchronizeRecord) *SynchronizeRecordDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *SynchronizeRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *SynchronizeRecordDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *SynchronizeRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(synchronizerecord.Table, sqlgraph.NewFieldSpec(synchronizerecord.FieldID, field.TypeInt))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// SynchronizeRecordDeleteOne is the builder for deleting a single SynchronizeRecord entity.
type SynchronizeRecordDeleteOne struct {
	srd *SynchronizeRecordDelete
}

// Where appends a list predicates to the SynchronizeRecordDelete builder.
func (srdo *SynchronizeRecordDeleteOne) Where(ps ...predicate.SynchronizeRecord) *SynchronizeRecordDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *SynchronizeRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{synchronizerecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *SynchronizeRecordDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
