// Code generated by ent, DO NOT EDIT.

package ent

import (
	"beetle/app/im/internal/data/ent/synchronizerecord"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SynchronizeRecordCreate is the builder for creating a SynchronizeRecord entity.
type SynchronizeRecordCreate struct {
	config
	mutation *SynchronizeRecordMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (src *SynchronizeRecordCreate) SetCreatedAt(t time.Time) *SynchronizeRecordCreate {
	src.mutation.SetCreatedAt(t)
	return src
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (src *SynchronizeRecordCreate) SetNillableCreatedAt(t *time.Time) *SynchronizeRecordCreate {
	if t != nil {
		src.SetCreatedAt(*t)
	}
	return src
}

// SetUpdatedAt sets the "updated_at" field.
func (src *SynchronizeRecordCreate) SetUpdatedAt(t time.Time) *SynchronizeRecordCreate {
	src.mutation.SetUpdatedAt(t)
	return src
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (src *SynchronizeRecordCreate) SetNillableUpdatedAt(t *time.Time) *SynchronizeRecordCreate {
	if t != nil {
		src.SetUpdatedAt(*t)
	}
	return src
}

// SetUserID sets the "user_id" field.
func (src *SynchronizeRecordCreate) SetUserID(i int) *SynchronizeRecordCreate {
	src.mutation.SetUserID(i)
	return src
}

// SetDeviceID sets the "device_id" field.
func (src *SynchronizeRecordCreate) SetDeviceID(u uuid.UUID) *SynchronizeRecordCreate {
	src.mutation.SetDeviceID(u)
	return src
}

// SetLastMessageID sets the "last_message_id" field.
func (src *SynchronizeRecordCreate) SetLastMessageID(i int64) *SynchronizeRecordCreate {
	src.mutation.SetLastMessageID(i)
	return src
}

// Mutation returns the SynchronizeRecordMutation object of the builder.
func (src *SynchronizeRecordCreate) Mutation() *SynchronizeRecordMutation {
	return src.mutation
}

// Save creates the SynchronizeRecord in the database.
func (src *SynchronizeRecordCreate) Save(ctx context.Context) (*SynchronizeRecord, error) {
	src.defaults()
	return withHooks(ctx, src.sqlSave, src.mutation, src.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (src *SynchronizeRecordCreate) SaveX(ctx context.Context) *SynchronizeRecord {
	v, err := src.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (src *SynchronizeRecordCreate) Exec(ctx context.Context) error {
	_, err := src.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (src *SynchronizeRecordCreate) ExecX(ctx context.Context) {
	if err := src.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (src *SynchronizeRecordCreate) defaults() {
	if _, ok := src.mutation.CreatedAt(); !ok {
		v := synchronizerecord.DefaultCreatedAt()
		src.mutation.SetCreatedAt(v)
	}
	if _, ok := src.mutation.UpdatedAt(); !ok {
		v := synchronizerecord.DefaultUpdatedAt()
		src.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (src *SynchronizeRecordCreate) check() error {
	if _, ok := src.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SynchronizeRecord.created_at"`)}
	}
	if _, ok := src.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SynchronizeRecord.updated_at"`)}
	}
	if _, ok := src.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SynchronizeRecord.user_id"`)}
	}
	if _, ok := src.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "SynchronizeRecord.device_id"`)}
	}
	if _, ok := src.mutation.LastMessageID(); !ok {
		return &ValidationError{Name: "last_message_id", err: errors.New(`ent: missing required field "SynchronizeRecord.last_message_id"`)}
	}
	return nil
}

func (src *SynchronizeRecordCreate) sqlSave(ctx context.Context) (*SynchronizeRecord, error) {
	if err := src.check(); err != nil {
		return nil, err
	}
	_node, _spec := src.createSpec()
	if err := sqlgraph.CreateNode(ctx, src.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	src.mutation.id = &_node.ID
	src.mutation.done = true
	return _node, nil
}

func (src *SynchronizeRecordCreate) createSpec() (*SynchronizeRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &SynchronizeRecord{config: src.config}
		_spec = sqlgraph.NewCreateSpec(synchronizerecord.Table, sqlgraph.NewFieldSpec(synchronizerecord.FieldID, field.TypeInt))
	)
	if value, ok := src.mutation.CreatedAt(); ok {
		_spec.SetField(synchronizerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := src.mutation.UpdatedAt(); ok {
		_spec.SetField(synchronizerecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := src.mutation.UserID(); ok {
		_spec.SetField(synchronizerecord.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := src.mutation.DeviceID(); ok {
		_spec.SetField(synchronizerecord.FieldDeviceID, field.TypeUUID, value)
		_node.DeviceID = value
	}
	if value, ok := src.mutation.LastMessageID(); ok {
		_spec.SetField(synchronizerecord.FieldLastMessageID, field.TypeInt64, value)
		_node.LastMessageID = value
	}
	return _node, _spec
}

// SynchronizeRecordCreateBulk is the builder for creating many SynchronizeRecord entities in bulk.
type SynchronizeRecordCreateBulk struct {
	config
	builders []*SynchronizeRecordCreate
}

// Save creates the SynchronizeRecord entities in the database.
func (srcb *SynchronizeRecordCreateBulk) Save(ctx context.Context) ([]*SynchronizeRecord, error) {
	specs := make([]*sqlgraph.CreateSpec, len(srcb.builders))
	nodes := make([]*SynchronizeRecord, len(srcb.builders))
	mutators := make([]Mutator, len(srcb.builders))
	for i := range srcb.builders {
		func(i int, root context.Context) {
			builder := srcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SynchronizeRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, srcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, srcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, srcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (srcb *SynchronizeRecordCreateBulk) SaveX(ctx context.Context) []*SynchronizeRecord {
	v, err := srcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (srcb *SynchronizeRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := srcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (srcb *SynchronizeRecordCreateBulk) ExecX(ctx context.Context) {
	if err := srcb.Exec(ctx); err != nil {
		panic(err)
	}
}
