// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"beetle/app/im/internal/data/ent/chatmessage"
	"beetle/app/im/internal/data/ent/loadrecord"
	"beetle/app/im/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatmessageMixin := schema.ChatMessage{}.Mixin()
	chatmessageMixinHooks1 := chatmessageMixin[1].Hooks()
	chatmessage.Hooks[0] = chatmessageMixinHooks1[0]
	chatmessageMixinInters1 := chatmessageMixin[1].Interceptors()
	chatmessage.Interceptors[0] = chatmessageMixinInters1[0]
	chatmessageMixinFields0 := chatmessageMixin[0].Fields()
	_ = chatmessageMixinFields0
	chatmessageFields := schema.ChatMessage{}.Fields()
	_ = chatmessageFields
	// chatmessageDescCreatedAt is the schema descriptor for created_at field.
	chatmessageDescCreatedAt := chatmessageMixinFields0[0].Descriptor()
	// chatmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatmessage.DefaultCreatedAt = chatmessageDescCreatedAt.Default.(func() time.Time)
	loadrecordMixin := schema.LoadRecord{}.Mixin()
	loadrecordMixinFields0 := loadrecordMixin[0].Fields()
	_ = loadrecordMixinFields0
	loadrecordFields := schema.LoadRecord{}.Fields()
	_ = loadrecordFields
	// loadrecordDescCreatedAt is the schema descriptor for created_at field.
	loadrecordDescCreatedAt := loadrecordMixinFields0[0].Descriptor()
	// loadrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	loadrecord.DefaultCreatedAt = loadrecordDescCreatedAt.Default.(func() time.Time)
}

const (
	Version = "v0.12.3"                                         // Version of ent codegen.
	Sum     = "h1:N5lO2EOrHpCH5HYfiMOCHYbo+oh5M8GjT0/cx5x6xkk=" // Sum of ent codegen.
)
