// Code generated by ent, DO NOT EDIT.

package ent

import (
	"beetle/app/user/internal/data/ent/group"
	"beetle/app/user/internal/data/ent/groupmember"
	"beetle/app/user/internal/data/ent/predicate"
	"beetle/app/user/internal/data/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// GroupMemberQuery is the builder for querying GroupMember entities.
type GroupMemberQuery struct {
	config
	ctx        *QueryContext
	order      []groupmember.OrderOption
	inters     []Interceptor
	predicates []predicate.GroupMember
	withGroup  *GroupQuery
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupMemberQuery builder.
func (gmq *GroupMemberQuery) Where(ps ...predicate.GroupMember) *GroupMemberQuery {
	gmq.predicates = append(gmq.predicates, ps...)
	return gmq
}

// Limit the number of records to be returned by this query.
func (gmq *GroupMemberQuery) Limit(limit int) *GroupMemberQuery {
	gmq.ctx.Limit = &limit
	return gmq
}

// Offset to start from.
func (gmq *GroupMemberQuery) Offset(offset int) *GroupMemberQuery {
	gmq.ctx.Offset = &offset
	return gmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gmq *GroupMemberQuery) Unique(unique bool) *GroupMemberQuery {
	gmq.ctx.Unique = &unique
	return gmq
}

// Order specifies how the records should be ordered.
func (gmq *GroupMemberQuery) Order(o ...groupmember.OrderOption) *GroupMemberQuery {
	gmq.order = append(gmq.order, o...)
	return gmq
}

// QueryGroup chains the current query on the "group" edge.
func (gmq *GroupMemberQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: gmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupmember.Table, groupmember.GroupColumn, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupmember.GroupTable, groupmember.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(gmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (gmq *GroupMemberQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: gmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupmember.Table, groupmember.UserColumn, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupmember.UserTable, groupmember.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(gmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupMember entity from the query.
// Returns a *NotFoundError when no GroupMember was found.
func (gmq *GroupMemberQuery) First(ctx context.Context) (*GroupMember, error) {
	nodes, err := gmq.Limit(1).All(setContextOp(ctx, gmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gmq *GroupMemberQuery) FirstX(ctx context.Context) *GroupMember {
	node, err := gmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single GroupMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupMember entity is found.
// Returns a *NotFoundError when no GroupMember entities are found.
func (gmq *GroupMemberQuery) Only(ctx context.Context) (*GroupMember, error) {
	nodes, err := gmq.Limit(2).All(setContextOp(ctx, gmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupmember.Label}
	default:
		return nil, &NotSingularError{groupmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gmq *GroupMemberQuery) OnlyX(ctx context.Context) *GroupMember {
	node, err := gmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of GroupMembers.
func (gmq *GroupMemberQuery) All(ctx context.Context) ([]*GroupMember, error) {
	ctx = setContextOp(ctx, gmq.ctx, "All")
	if err := gmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GroupMember, *GroupMemberQuery]()
	return withInterceptors[[]*GroupMember](ctx, gmq, qr, gmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gmq *GroupMemberQuery) AllX(ctx context.Context) []*GroupMember {
	nodes, err := gmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (gmq *GroupMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gmq.ctx, "Count")
	if err := gmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gmq, querierCount[*GroupMemberQuery](), gmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gmq *GroupMemberQuery) CountX(ctx context.Context) int {
	count, err := gmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gmq *GroupMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gmq.ctx, "Exist")
	switch _, err := gmq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gmq *GroupMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := gmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gmq *GroupMemberQuery) Clone() *GroupMemberQuery {
	if gmq == nil {
		return nil
	}
	return &GroupMemberQuery{
		config:     gmq.config,
		ctx:        gmq.ctx.Clone(),
		order:      append([]groupmember.OrderOption{}, gmq.order...),
		inters:     append([]Interceptor{}, gmq.inters...),
		predicates: append([]predicate.GroupMember{}, gmq.predicates...),
		withGroup:  gmq.withGroup.Clone(),
		withUser:   gmq.withUser.Clone(),
		// clone intermediate query.
		sql:  gmq.sql.Clone(),
		path: gmq.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (gmq *GroupMemberQuery) WithGroup(opts ...func(*GroupQuery)) *GroupMemberQuery {
	query := (&GroupClient{config: gmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gmq.withGroup = query
	return gmq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (gmq *GroupMemberQuery) WithUser(opts ...func(*UserQuery)) *GroupMemberQuery {
	query := (&UserClient{config: gmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gmq.withUser = query
	return gmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupMember.Query().
//		GroupBy(groupmember.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (gmq *GroupMemberQuery) GroupBy(field string, fields ...string) *GroupMemberGroupBy {
	gmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroupMemberGroupBy{build: gmq}
	grbuild.flds = &gmq.ctx.Fields
	grbuild.label = groupmember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GroupMember.Query().
//		Select(groupmember.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (gmq *GroupMemberQuery) Select(fields ...string) *GroupMemberSelect {
	gmq.ctx.Fields = append(gmq.ctx.Fields, fields...)
	sbuild := &GroupMemberSelect{GroupMemberQuery: gmq}
	sbuild.label = groupmember.Label
	sbuild.flds, sbuild.scan = &gmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GroupMemberSelect configured with the given aggregations.
func (gmq *GroupMemberQuery) Aggregate(fns ...AggregateFunc) *GroupMemberSelect {
	return gmq.Select().Aggregate(fns...)
}

func (gmq *GroupMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gmq); err != nil {
				return err
			}
		}
	}
	for _, f := range gmq.ctx.Fields {
		if !groupmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gmq.path != nil {
		prev, err := gmq.path(ctx)
		if err != nil {
			return err
		}
		gmq.sql = prev
	}
	return nil
}

func (gmq *GroupMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupMember, error) {
	var (
		nodes       = []*GroupMember{}
		_spec       = gmq.querySpec()
		loadedTypes = [2]bool{
			gmq.withGroup != nil,
			gmq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GroupMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GroupMember{config: gmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gmq.withGroup; query != nil {
		if err := gmq.loadGroup(ctx, query, nodes, nil,
			func(n *GroupMember, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := gmq.withUser; query != nil {
		if err := gmq.loadUser(ctx, query, nodes, nil,
			func(n *GroupMember, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gmq *GroupMemberQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*GroupMember, init func(*GroupMember), assign func(*GroupMember, *Group)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GroupMember)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gmq *GroupMemberQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*GroupMember, init func(*GroupMember), assign func(*GroupMember, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GroupMember)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gmq *GroupMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gmq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, gmq.driver, _spec)
}

func (gmq *GroupMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(groupmember.Table, groupmember.Columns, nil)
	_spec.From = gmq.sql
	if unique := gmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gmq.path != nil {
		_spec.Unique = true
	}
	if fields := gmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if gmq.withGroup != nil {
			_spec.Node.AddColumnOnce(groupmember.FieldGroupID)
		}
		if gmq.withUser != nil {
			_spec.Node.AddColumnOnce(groupmember.FieldUserID)
		}
	}
	if ps := gmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gmq *GroupMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gmq.driver.Dialect())
	t1 := builder.Table(groupmember.Table)
	columns := gmq.ctx.Fields
	if len(columns) == 0 {
		columns = groupmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gmq.sql != nil {
		selector = gmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gmq.ctx.Unique != nil && *gmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gmq.predicates {
		p(selector)
	}
	for _, p := range gmq.order {
		p(selector)
	}
	if offset := gmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroupMemberGroupBy is the group-by builder for GroupMember entities.
type GroupMemberGroupBy struct {
	selector
	build *GroupMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gmgb *GroupMemberGroupBy) Aggregate(fns ...AggregateFunc) *GroupMemberGroupBy {
	gmgb.fns = append(gmgb.fns, fns...)
	return gmgb
}

// Scan applies the selector query and scans the result into the given value.
func (gmgb *GroupMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gmgb.build.ctx, "GroupBy")
	if err := gmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupMemberQuery, *GroupMemberGroupBy](ctx, gmgb.build, gmgb, gmgb.build.inters, v)
}

func (gmgb *GroupMemberGroupBy) sqlScan(ctx context.Context, root *GroupMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gmgb.fns))
	for _, fn := range gmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gmgb.flds)+len(gmgb.fns))
		for _, f := range *gmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GroupMemberSelect is the builder for selecting fields of GroupMember entities.
type GroupMemberSelect struct {
	*GroupMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gms *GroupMemberSelect) Aggregate(fns ...AggregateFunc) *GroupMemberSelect {
	gms.fns = append(gms.fns, fns...)
	return gms
}

// Scan applies the selector query and scans the result into the given value.
func (gms *GroupMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gms.ctx, "Select")
	if err := gms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupMemberQuery, *GroupMemberSelect](ctx, gms.GroupMemberQuery, gms, gms.inters, v)
}

func (gms *GroupMemberSelect) sqlScan(ctx context.Context, root *GroupMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gms.fns))
	for _, fn := range gms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
