apiVersion: v1
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:9100
        timeout: 1s
    data:
      database:
        driver: mysql
        source: root:123456@tcp(db-tcp:3306)/filesystem?parseTime=true
      redis:
        addr: 127.0.0.1:6379
        read_timeout: 0.2s
        write_timeout: 0.2s
    auth:
      jwt_key: testkey
      jwt_exp: 360000
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: filesystem
  name: filesystem-cm0
