apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: im-svc
  name: im-svc-cm0
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
      websocket:
        addr: 0.0.0.0:10000
        path: /ws
    data:
      database:
        driver: mysql
        source: root:123456@tcp(im-db-tcp:3306)/beetle_im?parseTime=true
      redis:
        addr: 127.0.0.1:6379
        read_timeout: 0.2s
        write_timeout: 0.2s
    auth:
      jwt_key: testkey
