// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GroupChatMessage is the predicate function for groupchatmessage builders.
type GroupChatMessage func(*sql.Selector)

// PersonalChatMessage is the predicate function for personalchatmessage builders.
type PersonalChatMessage func(*sql.Selector)

// SynchronizeRecord is the predicate function for synchronizerecord builders.
type SynchronizeRecord func(*sql.Selector)
